
name: CI-CD Frontend pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

        
    - name: Install dependencies
      working-directory: ./frontend/app
      run: npm ci


    - name: Run Vite build
      working-directory: ./frontend/app
      run: npm run build

      
    - name: Run test
      working-directory: ./frontend/app
      run: npm test


    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    
    - name: Azure ACR login
      run: az acr login --name briitzacr


    - name: Build Docker image
      working-directory: ./frontend/app
      run: docker build -t briitzacr.azurecr.io/frontend:v1 .


    - name: Push Docker image to ACR
      run: docker push briitzacr.azurecr.io/frontend:v1


    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: briitz
        cluster-name: briitzCluster


    - name: Deploy to AKS
      run: |
        kubectl apply -f ./frontend/app/k8s/frontend-deployment.yaml
        kubectl apply -f ./frontend/app/k8s/frontend-service.yaml
        kubectl apply -f ./frontend/app/k8s/frontend-hpa.yaml 
