
name: CICD Frontend pipeline

on:
  push:
    paths:
      - 'frontend/app/**'
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        

    - name: Install dependencies
      working-directory: ./frontend/app
      run: npm ci


    - name: Run Vite build
      working-directory: ./frontend/app
      run: npm run build
      

    - name: Run test
      working-directory: ./frontend/app
      run: npm test
